"""Initial migration: users, posts, projects, profiles

Revision ID: 947c17daa5cf
Revises: 1bad9eafe6eb
Create Date: 2025-10-25 19:14:46.507237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '947c17daa5cf'
down_revision: Union[str, Sequence[str], None] = '1bad9eafe6eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
